# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dc5ee93dfe63c1e8a9a789e7ab8163ba6ffba9567030b71c13eef1a8e2920f250e05e7a0815a883cf66b4b3497b8964e2ff9e9b9b7c7f30c2dc486331136bed

test:
  secret_key_base: 4ed0f5d67c77268e516d8571616783874f59377118e6d29df35f79c99fcb189e4c1471a0f8a3d74af7c3b7831f3594d6a1cf7ed94d7464db142b4fc237d2a1f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
